# Generated by Django 5.0.1 on 2024-04-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
