# Generated by Django 5.0.1 on 2024-04-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_user_reviews_student'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
