# Generated by Django 5.0.1 on 2024-04-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_reviews_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mobile_num',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
