# Generated by Django 5.0.1 on 2024-04-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_enroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='course',
        ),
        migrations.AddField(
            model_name='enroll',
            name='course',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
