# Generated by Django 5.0.1 on 2024-04-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_enroll_course_enroll_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
