# Generated by Django 5.0.1 on 2024-04-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mobile_num',
            field=models.CharField(max_length=12),
        ),
    ]
