# Generated by Django 5.0.1 on 2024-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_image_alter_course_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
