# Generated by Django 5.0.1 on 2024-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='course',
        ),
        migrations.AddField(
            model_name='enroll',
            name='course',
            field=models.ManyToManyField(null=True, to='course.course'),
        ),
    ]
