# Generated by Django 5.0.1 on 2024-05-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_enroll_student'),
        ('student', '0003_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='course',
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
